### ISSUE TITLE
VectorTile layer for roads used in summary

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-road-distance-sdg#15]
As result of summary we should have a vector tile layer that includes the OSM road features.
Road features should include a flag that indicates if it was included or excluded in the analysis

The issue is to run these locally on Malawi and South Africa

**Comment by CloudNiner** [comment]
How do we aggregate? Ross, Jeff and I discussed a first pass that includes all roads at max zoom and then filters to only show included roads at higher zoom level. Otherwise, there's a path that dumps the road network as geojson and aggregate via tippecanoe. Concern is that as we zoom up there's way too many roads to include.
