### ISSUE TITLE
Global Output output

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-road-distance-sdg#20]
- Image pyramid per country
- road pyramid per country (vector tyles)

Note: The current implementation is centered around DataFrames and is being frugal with memory usage so this is expected to be "alright". But as always we can expect this to be a sizable chunk of work to deal with any performance considerations and baby-sit the job.

**Comment by CloudNiner** [comment]
This is starting to look non-trivial. When generating the gloabal layer, we need to:

- Generate one vector tile layer for the whole globe
- Add country name as additional property in all vector tile layers so we can filter features by country

**Comment by echeipesh** [comment]
Do we need to unify the vector tile layers? What would be the visual artifact of adding each country as their own layer?

**Comment by CloudNiner** [comment]
You'd just have an absurd number of layers, which is a pain to configure client side

**Comment by CloudNiner** [comment]
A less-ideal backup would be to just bake each layer for each country and the UI can show the global choropleth and when a country is clicked it zooms and shows this full vector tile layer for the clicked country.

**Comment by echeipesh** [comment]
Lets imagine this global layer. What happens when a rendered cell intersects two or more countries? They need to be individual objects so they can be filtered (presumably (in-tile) vector tile layer per country)) but what does that do that mean for choropleth ?

**Comment by rossbernet** [comment]
After speaking with @jfrankl and @CloudNiner this morning, then @echeipesh in the afternoon, it seems like it's going to make it much more simple to generate this output on a per country basis, rather than one global layer that contains all countries. 

I think it is sufficient if we can visualize the results of the choropleth at a global scale and compare countries to countries that way. 

And then for the more detailed, "rasterized" view (via the vector tiles approach), we can just generate these layers one country at a time. I think that will simplify things considerably and not jeopardize the impressiveness of the visual too much. 

Do we know if it is a problem to have 200+ vector tile layers (one for each country) on the app? @jfrankl

**Comment by CloudNiner** [comment]
Closed by #37 and the release at: https://github.com/geotrellis/geotrellis-road-distance-sdg/releases/tag/v3.0
